fix ci

diff --git a/.github/workflows/.github.ci.yml b/.github/workflows/.github.ci.yml
--- a/.github/workflows/.github.ci.yml
+++ b/.github/workflows/.github.ci.yml
@@ -17,7 +17,7 @@ jobs:
       id: run_install
       run: |
         python -m pip install --upgrade pip 
-        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
+        pip install flake8 pep8-naming flake8-broken-line flake8-return 
         pip install -r backend/requirements.txt 
         
     - name: Test with flake8
@@ -83,35 +83,36 @@ jobs:
             Ошибка при сборке/отправке образа на DockerHub  - ${{ github.repository }}
             https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
-  deploy:
-    name: Deploy to server
-    runs-on: ubuntu-latest
-    needs: build_and_push_to_docker_hub
-    steps:
-      - name: Deploy
-        run: |
-          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
-          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
-          sudo apt update && sudo apt install ngrok
-          ngrok config add-authtoken ${{ secrets.NGROK_SECRET_KEY }}
-          ngrok http 8000 --log=stdout > ngrok.log 2>&1 &
-          sleep 5
-          if ! pgrep ngrok > /dev/null; then
-            echo "Failed to start ngrok"
-            cat ngrok.log
-            exit 1
-          fi
-          curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
-          if [ ! -s tunnels.json ]; then
-            echo "Failed to get ngrok tunnels"
-            cat ngrok.log
-            exit 1
-          fi
-    
+        
+            deploy:
+                name: Deploy to server
+                runs-on: ubuntu-latest
+                needs: build_and_push_to_docker_hub
+                steps:
+                  - name: Deploy
+                    run: |
+                      curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
+                      echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
+                      sudo apt update && sudo apt install ngrok
+                      ngrok config add-authtoken ${{ secrets.NGROK_SECRET_KEY }}
+                      ngrok http 8000 --log=stdout > ngrok.log 2>&1 &
+                      sleep 5
+                      if ! pgrep ngrok > /dev/null; then
+                        echo "Failed to start ngrok"
+                        cat ngrok.log
+                        exit 1
+                      fi
+                      curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
+                      if [ ! -s tunnels.json ]; then
+                        echo "Failed to get ngrok tunnels"
+                        cat ngrok.log
+                        exit 1
+                      fi
+              
   send_message:
     name: Send success message
     runs-on: ubuntu-latest
-    needs: deploy
+    needs: build_and_push_to_docker_hub
     steps:
     - name: send message
       uses: appleboy/telegram-action@master
