fix pep8

diff --git a/.github/workflows/.github.ci.yml b/.github/workflows/.github.ci.yml
--- a/.github/workflows/.github.ci.yml
+++ b/.github/workflows/.github.ci.yml
@@ -1,4 +1,4 @@
-name: foodgram-project-react workflow
+name: foodgram-project workflow
 
 on: [push]
 
@@ -83,31 +83,30 @@ jobs:
             Ошибка при сборке/отправке образа на DockerHub  - ${{ github.repository }}
             https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
-        
-            deploy:
-                name: Deploy to server
-                runs-on: ubuntu-latest
-                needs: build_and_push_to_docker_hub
-                steps:
-                  - name: Deploy
-                    run: |
-                      curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
-                      echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
-                      sudo apt update && sudo apt install ngrok
-                      ngrok config add-authtoken ${{ secrets.NGROK_SECRET_KEY }}
-                      ngrok http 8000 --log=stdout > ngrok.log 2>&1 &
-                      sleep 5
-                      if ! pgrep ngrok > /dev/null; then
-                        echo "Failed to start ngrok"
-                        cat ngrok.log
-                        exit 1
-                      fi
-                      curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
-                      if [ ! -s tunnels.json ]; then
-                        echo "Failed to get ngrok tunnels"
-                        cat ngrok.log
-                        exit 1
-                      fi
+  deploy:
+    name: Deploy to server
+    runs-on: ubuntu-latest
+    needs: build_and_push_to_docker_hub
+    steps:
+      - name: Deploy
+        run: |
+          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
+          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
+          sudo apt update && sudo apt install ngrok
+          ngrok config add-authtoken ${{ secrets.NGROK_SECRET_KEY }}
+          ngrok http 8000 --log=stdout > ngrok.log 2>&1 &
+          sleep 5
+          if ! pgrep ngrok > /dev/null; then
+            echo "Failed to start ngrok"
+            cat ngrok.log
+            exit 1
+          fi
+          curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
+          if [ ! -s tunnels.json ]; then
+            echo "Failed to get ngrok tunnels"
+            cat ngrok.log
+            exit 1
+          fi
               
   send_message:
     name: Send success message
@@ -119,4 +118,4 @@ jobs:
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
-        message: Ура !  ${{ github.workflow }} для репозитория ${{ github.repository }} успешно выполнен!
+        message: Ура !  ${{ github.workflow }} для репозитория ${{ github.repository }} успешно выполнен! 
